"""initial catalog schema

Revision ID: e7780a90b130
Revises: 
Create Date: 2026-06-25 04:33:23.019961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e7780a90b130'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('featuredmajor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('featuredmajor', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_featuredmajor_slug'), ['slug'], unique=True)

    op.create_table('featuredrotationrule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('frequency_days', sa.Integer(), nullable=False),
    sa.Column('window_size', sa.Integer(), nullable=False),
    sa.Column('ordered_slugs', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type'),
    sa.UniqueConstraint('entity_type', name='uq_featured_rotation_rules_entity_type')
    )
    op.create_table('featuredschool',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('hero_image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('featuredschool', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_featuredschool_slug'), ['slug'], unique=True)

    op.create_table('major',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('discipline', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('recommended_regions', sa.JSON(), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sections', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('major', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_major_discipline'), ['discipline'], unique=False)
        batch_op.create_index(batch_op.f('ix_major_slug'), ['slug'], unique=True)

    op.create_table('mediaanalysisevent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('media_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('media_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rendered_reply', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('extracted_fields', sa.JSON(), nullable=False),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.Column('auto_routed_to_chat', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mediaanalysisevent', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mediaanalysisevent_channel'), ['channel'], unique=False)
        batch_op.create_index(batch_op.f('ix_mediaanalysisevent_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_mediaanalysisevent_media_id'), ['media_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mediaanalysisevent_media_type'), ['media_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_mediaanalysisevent_message_id'), ['message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mediaanalysisevent_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_mediaanalysisevent_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_mediaanalysisevent_user_id'), ['user_id'], unique=False)

    op.create_table('reviewqueue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('candidate_version', sa.Integer(), nullable=True),
    sa.Column('diff_summary', sa.JSON(), nullable=False),
    sa.Column('priority', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('review_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reviewed_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('review_note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reviewqueue', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reviewqueue_entity_id'), ['entity_id'], unique=False)

    op.create_table('runtimesetting',
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('school',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('region', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sections', sa.JSON(), nullable=False),
    sa.Column('website', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('school', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_school_region'), ['region'], unique=False)
        batch_op.create_index(batch_op.f('ix_school_slug'), ['slug'], unique=True)

    op.create_table('searchentry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quick_prompts', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userentitlement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entitlement', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'entitlement', name='uq_user_entitlements_user_id_entitlement')
    )
    with op.batch_alter_table('userentitlement', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_userentitlement_entitlement'), ['entitlement'], unique=False)
        batch_op.create_index(batch_op.f('ix_userentitlement_user_id'), ['user_id'], unique=False)

    op.create_table('majorrankingreference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('major_id', sa.Integer(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scope', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['major_id'], ['major.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('major_id', 'source', 'year', name='uq_major_ranking_references_major_source_year')
    )
    with op.batch_alter_table('majorrankingreference', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_majorrankingreference_major_id'), ['major_id'], unique=False)

    op.create_table('schoolcontentversion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'published', 'archived', name='versionstatus'), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('published_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'version', name='uq_school_content_versions_school_id_version')
    )
    with op.batch_alter_table('schoolcontentversion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schoolcontentversion_school_id'), ['school_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_schoolcontentversion_status'), ['status'], unique=False)
        batch_op.create_index('uq_school_content_versions_one_published_per_school', ['school_id'], unique=True, sqlite_where=sa.text("status = 'published'"))

    op.create_table('schoolmajorrelation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('major_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['major_id'], ['major.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'major_id', name='uq_school_major_relations_school_major')
    )
    with op.batch_alter_table('schoolmajorrelation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schoolmajorrelation_major_id'), ['major_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_schoolmajorrelation_school_id'), ['school_id'], unique=False)

    op.create_table('schoolrankingreference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scope', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'source', 'year', name='uq_school_ranking_references_school_source_year')
    )
    with op.batch_alter_table('schoolrankingreference', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schoolrankingreference_school_id'), ['school_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schoolrankingreference', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schoolrankingreference_school_id'))

    op.drop_table('schoolrankingreference')
    with op.batch_alter_table('schoolmajorrelation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schoolmajorrelation_school_id'))
        batch_op.drop_index(batch_op.f('ix_schoolmajorrelation_major_id'))

    op.drop_table('schoolmajorrelation')
    with op.batch_alter_table('schoolcontentversion', schema=None) as batch_op:
        batch_op.drop_index('uq_school_content_versions_one_published_per_school', sqlite_where=sa.text("status = 'published'"))
        batch_op.drop_index(batch_op.f('ix_schoolcontentversion_status'))
        batch_op.drop_index(batch_op.f('ix_schoolcontentversion_school_id'))

    op.drop_table('schoolcontentversion')
    with op.batch_alter_table('majorrankingreference', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_majorrankingreference_major_id'))

    op.drop_table('majorrankingreference')
    with op.batch_alter_table('userentitlement', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_userentitlement_user_id'))
        batch_op.drop_index(batch_op.f('ix_userentitlement_entitlement'))

    op.drop_table('userentitlement')
    op.drop_table('searchentry')
    with op.batch_alter_table('school', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_school_slug'))
        batch_op.drop_index(batch_op.f('ix_school_region'))

    op.drop_table('school')
    op.drop_table('runtimesetting')
    with op.batch_alter_table('reviewqueue', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reviewqueue_entity_id'))

    op.drop_table('reviewqueue')
    with op.batch_alter_table('mediaanalysisevent', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mediaanalysisevent_user_id'))
        batch_op.drop_index(batch_op.f('ix_mediaanalysisevent_status'))
        batch_op.drop_index(batch_op.f('ix_mediaanalysisevent_source'))
        batch_op.drop_index(batch_op.f('ix_mediaanalysisevent_message_id'))
        batch_op.drop_index(batch_op.f('ix_mediaanalysisevent_media_type'))
        batch_op.drop_index(batch_op.f('ix_mediaanalysisevent_media_id'))
        batch_op.drop_index(batch_op.f('ix_mediaanalysisevent_created_at'))
        batch_op.drop_index(batch_op.f('ix_mediaanalysisevent_channel'))

    op.drop_table('mediaanalysisevent')
    with op.batch_alter_table('major', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_major_slug'))
        batch_op.drop_index(batch_op.f('ix_major_discipline'))

    op.drop_table('major')
    with op.batch_alter_table('featuredschool', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_featuredschool_slug'))

    op.drop_table('featuredschool')
    op.drop_table('featuredrotationrule')
    with op.batch_alter_table('featuredmajor', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_featuredmajor_slug'))

    op.drop_table('featuredmajor')
    # ### end Alembic commands ###
